name: Publish AsciiDoc as eBook Release

on:
  push:
    branches:
      - master

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'

    - name: Install Asciidoctor and Dependencies
      run: |
        gem install asciidoctor asciidoctor-pdf asciidoctor-epub3 rouge
        
    - name: Convert AsciiDoc to PDF
      run: |
        mkdir -p output
        asciidoctor-pdf -D output book.asciidoc

    - name: Convert AsciiDoc to EPUB
      run: |
        asciidoctor-epub3 -D output book.asciidoc

    - name: Copy Additional Resources
      run: cp -r images output/

    - name: Create Release Artifacts
      run: |
        cd output
        zip mastering-bitcoin.zip *.pdf *.epub

    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          output/mastering-bitcoin.zip
          output/book.pdf
          output/book.epub
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: v1.0.0
        name: "Mastering Bitcoin eBook Release"
        body: |
          This release includes the latest version of the Mastering Bitcoin eBook in PDF and EPUB formats.
