name: Build and Publish Book

on:
  push:
    branches:
      - master

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'

    - name: Install Asciidoctor
      run: |
        gem install asciidoctor
        gem install asciidoctor-pdf
        # Add other necessary tools or plugins here

    - name: Compile Book to PDF
      run: asciidoctor-pdf -D output book.asciidoc
      # Replace book.asciidoc with your main file if different

    - name: Compile Other Formats
      run: |
        # Add commands to generate other formats here

    - name: Upload to GitHub Releases
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./output/book.pdf
        asset_name: book.pdf
        asset_content_type: application/pdf
        # Repeat for other formats

